### PR TITLE
Gravitational Wave lecture

### PR DESCRIPTION
**Pull request by reedessick**
I've added a notebook and supporting data file for the Gravitational Wave lecture. The notebook contains a decent amount of introduction, some magic formulas (which I'll explain a bit more in person), and then a relatively quick activity to estimate the Hubble constant from simulated data.

Please let me know if you'd like anything changed or need me to do anything else. Looking forward to the lecture!

### CODE REVIEW

**Comment by chihway** [comment]
Thanks @reedessick , this looks good. The only comment I have is that the figure doesn't show for me.  Also you will be talking through the intro bit, correct? lemme know if you think 30 min is enough for all of this.

**Comment by reedessick** [comment]
Shoot. I'll see if I can get the picture to show up.

My plan was to go through the intro stuff for about 20 min and then ask the students to work through the example for the remaining 10 min. I think that'll work.

**Comment by reedessick** [comment]
I'm not sure how to get the image to render properly within the notebook, but I went ahead and added a copy of the png to the repo. If it doesn't show up within the notebook, students should still be able to navigate to it as needed.

let me know if you think anything else needs work.

**Comment by chihway** [comment]
Ok, yeah that looks good. I'll merge it now and maybe play with the figure insertion a little. But otherwise you're good to go!

**Comment by chihway** [comment]
Actually, the image displays just fine when running on midway, for some reason it just doesn't like the github interface.

**Pull request merged**
